### ISSUE TITLE
Add in probe on frontend to clean up K8s logs

### ISSUE THREAD

**Issue by dazdaz** [GoogleCloudPlatform/bank-of-anthos#261] opened 2020-07-03 09:28 UTC
kubectl get events

65s         Warning   Unhealthy           pod/frontend-557f465b6f-xqz9q
Readiness probe failed: Get http://10.1.010.10:8080/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by askmeegs** [comment] 2020-08-17 18:16
Duplicate of #265

**Closed by askmeegs** 2020-08-17 18:16 UTC
