### ISSUE TITLE
Multi-regional CloudSQL with replication

### ISSUE THREAD

**Issue by ameer00** [GoogleCloudPlatform/bank-of-anthos#1015] opened 2022-10-13 22:16 UTC
It appears that the current multi-regional architecture with CloudSQL uses CloudSQL in a single region. 
Would be great if that CloudSQL can replicate to the second region (for HA, redundancy).

**Comment by bourgeoisor** [comment] 2023-04-26 21:34
Closing as dupe of https://github.com/GoogleCloudPlatform/bank-of-anthos/issues/185

**Closed by bourgeoisor** 2023-04-26 21:34 UTC
Labels: type: feature request, priority: p3
