### ISSUE TITLE
Multiple services broken

### ISSUE THREAD

**Issue by piyushsachdeva** [GoogleCloudPlatform/bank-of-anthos#1971] opened 2024-01-02 19:49 UTC
### Describe the bug 

Hi,

I have created a new AKS cluster on Azure and deployed the application using the instructions given in readme after disabling TRACE and METRICS as this is a non-GKE cluster; however, a few of the pods are stuck in CRASHLOOPBACK STATE.

### To Reproduce 
Followed the steps as per README

### Logs  
Logs from balance reader below:

```
:3.1.5]
        at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:85) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:261) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:235) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:52) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4850) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source) ~[?:?]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:845) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source) ~[?:?]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:240) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:917) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:488) ~[tomcat-embed-core-10.1.15.jar:10.1.15]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:489) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:211) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:183) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-3.1.5.jar:3.1.5]
        ... 8 more
```

### Screenshots 

piyush [ ~ ]$ kubectl get pods

```
NAME                                  READY   STATUS             RESTARTS        AGE
accounts-db-0                         1/1     Running            0               35m
balancereader-5cfddbbdb8-j98rr        0/1     CrashLoopBackOff   5 (2m32s ago)   7m53s
contacts-5b9d98844b-zwcd8             1/1     Running            0               35m
frontend-cc478cdb9-98g2f              1/1     Running            0               35m
ledger-db-0                           1/1     Running            0               35m
ledgerwriter-69fbd4f544-sqxwz         0/1     CrashLoopBackOff   5 (2m17s ago)   7m53s
loadgenerator-7c445568c9-5gmhf        1/1     Running            0               8m17s
transactionhistory-75b767f5cb-mdld5   0/1     CrashLoopBackOff   5 (2m44s ago)   7m52s
userservice-75bd77f9fb-ncwmv          1/1     Running            0               35m
```

### Environment 
 Linux
 AKS 1.27.7

### Additional context 

I see some dependencies were updated in pom.xml 5 days ago, could that be broken?

### Exposure 

persistent

**Comment by bourgeoisor** [comment] 2024-01-03 16:45
Hi @piyushsachdeva! Which commit did you use for this build, and which README steps did you follow exactly (could you paste the commands)?

I just did a fresh deployment with the latest commit and I didn't see any issues:
```
~ kubectl get pods
NAME                                  READY   STATUS    RESTARTS   AGE
accounts-db-0                         1/1     Running   0          18m
balancereader-b5bfdd8b4-rkh4c         1/1     Running   0          17m
contacts-849b5f4b89-s8vpf             1/1     Running   0          18m
frontend-64dccf9f6b-gwdcf             1/1     Running   0          13m
ledger-db-0                           1/1     Running   0          17m
ledgerwriter-64fc58486f-jrft5         1/1     Running   0          16m
loadgenerator-7944c679d4-jpzq8        1/1     Running   0          13m
transactionhistory-6f455cf4db-8fc6s   1/1     Running   0          15m
userservice-7c86845986-cql68          1/1     Running   0          18m
```

**Comment by piyushsachdeva** [comment] 2024-01-03 17:23
Thank you for looking into this as a priority. I used the latest commit and the below readme,
https://github.com/GoogleCloudPlatform/bank-of-anthos/blob/main/docs/environments.md

**Comment by piyushsachdeva** [comment] 2024-01-03 18:33
By the way I am running this on Azure Kubernetes Service AKS 1.27.7

**Comment by bourgeoisor** [comment] 2024-01-03 19:36
Did another deploy this time with those commands (instead of `skaffold deploy` which I used earlier) and it still seems fine:

```
~ kubectl get pods
NAME                                 READY   STATUS    RESTARTS   AGE
accounts-db-0                        1/1     Running   0          21m
balancereader-7886d64496-frctm       1/1     Running   0          21m
contacts-6f878655cf-6qmww            1/1     Running   0          21m
frontend-7d76855878-qmsj9            1/1     Running   0          21m
ledger-db-0                          1/1     Running   0          21m
ledgerwriter-5b97f6777b-rrffl        1/1     Running   0          21m
loadgenerator-58664c4dc5-5ghvm       1/1     Running   0          21m
transactionhistory-96986d648-xj8p2   1/1     Running   0          21m
userservice-5f5589c9-wlfsf           1/1     Running   0          21m
```

Granted this is on GKE (I don't have easy access to Azure) but this likely precludes that something is wrong / broken in the POMs (as far as dependency versioning is concerned anyway).

I have a hard time parsing your stacktrace since it's not complete (8 lines missing) and I don't see any lines in there pertaining to Bank of Anthos source code specifically. Are there any other interesting logs?

Bumping the bug down to p2 because I can't reproduce on GKE (our only officially supported deployment platform) in either of the deployment options for both latest commit and the latest official release.

**Comment by piyushsachdeva** [comment] 2024-01-04 16:27
`but this likely precludes that something is wrong / broken in the POMs (as far as dependency versioning is concerned anyway).`
I totally agree with you on this.

I destroyed my cluster now. Will share the complete logs shortly after I reproduce the issue.

**Comment by bourgeoisor** [comment] 2024-01-23 22:10
@piyushsachdeva I will close this issue but if you run into this again feel free to reopen / let me know!

**Closed by bourgeoisor** 2024-01-23 22:10 UTC
Labels: type: bug, priority: p2
